Host: charliepoole.org
SiteTitle: CharliePoole.org
LinkHideExtensions: false
PostSources: "{technical,personal}/*"
LastUpdate: => { if (Document.ContainsKey("Updated")) return Document.GetDateTime("Updated"); return Document.GetDateTime("Published"); };